name: Elixir CI

on: push

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        elixir-version: ["1.13", "1.14"]
        otp-version: ["23", "24", "25"]
        include:
          - elixir-version: "1.12"
            otp-version: "24"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir-version }}
          otp-version: ${{ matrix.otp-version }}

      - name: Install dependencies
        run: mix deps.get
      - name: Compile deps
        run: MIX_ENV=test mix deps.compile
      - name: Compile
        run: MIX_ENV=test mix compile --warnings-as-errors
      - name: Run tests
        run: mix test --warnings-as-errors
      - name: Check format
        run: mix format --check-formatted

  # integration_test:
  #   name: Integration test
  #   runs-on: ubuntu-18.04

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Elixir
  #       uses: erlef/setup-beam@v1
  #       with:
  #         elixir-version: "1.14"
  #         otp-version: "25"

  #     - name: Install dependencies
  #       run: mix deps.get
  #     - name: Compile deps
  #       run: MIX_ENV=test mix deps.compile
  #     - name: Compile
  #       run: MIX_ENV=test mix compile --warnings-as-errors
  #     - name: Run tests
  #       run: mix test --only integration --warnings-as-errors
